default: &DEFAULT
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password:
  host: localhost
  pool: 128
  # host: shinebox

development: &DEVELOPMENT
  <<: *DEFAULT
  database: trails_forward_development

test: &TEST
  <<: *DEFAULT
  adapter: sqlite3
  database: trails_forward_test

cucumber:
  <<: *TEST
